require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DummyUsersController do

  # This should return the minimal set of attributes required to create a valid
  # DummyUser. As you add validations to DummyUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DummyUsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dummy_users as @dummy_users" do
      dummy_user = DummyUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dummy_users).should eq([dummy_user])
    end
  end

  describe "GET show" do
    it "assigns the requested dummy_user as @dummy_user" do
      dummy_user = DummyUser.create! valid_attributes
      get :show, {:id => dummy_user.to_param}, valid_session
      assigns(:dummy_user).should eq(dummy_user)
    end
  end

  describe "GET new" do
    it "assigns a new dummy_user as @dummy_user" do
      get :new, {}, valid_session
      assigns(:dummy_user).should be_a_new(DummyUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested dummy_user as @dummy_user" do
      dummy_user = DummyUser.create! valid_attributes
      get :edit, {:id => dummy_user.to_param}, valid_session
      assigns(:dummy_user).should eq(dummy_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DummyUser" do
        expect {
          post :create, {:dummy_user => valid_attributes}, valid_session
        }.to change(DummyUser, :count).by(1)
      end

      it "assigns a newly created dummy_user as @dummy_user" do
        post :create, {:dummy_user => valid_attributes}, valid_session
        assigns(:dummy_user).should be_a(DummyUser)
        assigns(:dummy_user).should be_persisted
      end

      it "redirects to the created dummy_user" do
        post :create, {:dummy_user => valid_attributes}, valid_session
        response.should redirect_to(DummyUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dummy_user as @dummy_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        DummyUser.any_instance.stub(:save).and_return(false)
        post :create, {:dummy_user => {}}, valid_session
        assigns(:dummy_user).should be_a_new(DummyUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DummyUser.any_instance.stub(:save).and_return(false)
        post :create, {:dummy_user => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dummy_user" do
        dummy_user = DummyUser.create! valid_attributes
        # Assuming there are no other dummy_users in the database, this
        # specifies that the DummyUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DummyUser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dummy_user.to_param, :dummy_user => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dummy_user as @dummy_user" do
        dummy_user = DummyUser.create! valid_attributes
        put :update, {:id => dummy_user.to_param, :dummy_user => valid_attributes}, valid_session
        assigns(:dummy_user).should eq(dummy_user)
      end

      it "redirects to the dummy_user" do
        dummy_user = DummyUser.create! valid_attributes
        put :update, {:id => dummy_user.to_param, :dummy_user => valid_attributes}, valid_session
        response.should redirect_to(dummy_user)
      end
    end

    describe "with invalid params" do
      it "assigns the dummy_user as @dummy_user" do
        dummy_user = DummyUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DummyUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => dummy_user.to_param, :dummy_user => {}}, valid_session
        assigns(:dummy_user).should eq(dummy_user)
      end

      it "re-renders the 'edit' template" do
        dummy_user = DummyUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DummyUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => dummy_user.to_param, :dummy_user => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dummy_user" do
      dummy_user = DummyUser.create! valid_attributes
      expect {
        delete :destroy, {:id => dummy_user.to_param}, valid_session
      }.to change(DummyUser, :count).by(-1)
    end

    it "redirects to the dummy_users list" do
      dummy_user = DummyUser.create! valid_attributes
      delete :destroy, {:id => dummy_user.to_param}, valid_session
      response.should redirect_to(dummy_users_url)
    end
  end

end
